import assert from 'node:assert/strict';
import fs from 'node:fs';
import{fresh,blank,total,powerOK,validSquads,validState,encodeShare,decodeShare}from'../dist/core.mjs';
import{positionLabel,skillSummary}from'../dist/formation.mjs';
import{formationExtras}from'../dist/formation-view.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../dist/data/cards.json',import.meta.url)));const ids=new Set(data.cards.map(c=>c.id));const id=data.cards[0].id;
assert.equal(ids.size,data.cards.length);assert.equal(data.cards.length,234);assert.ok(data.cards.every(c=>c.dataStatus==='complete'&&c.image.startsWith('https://')&&c.skills.active));
assert.equal(blank('nyan').length,1);assert.equal(blank('arena').length,4);assert.equal(blank('incident').length,4);
for(const p of [0,-1,10000,1.5,NaN])assert.equal(powerOK(p),false);for(const p of [1,125,9999])assert.ok(powerOK(p));
const s=fresh();s.owned[id]=125;s.current.arena[0][0]={id,power:125};s.current.arena[1][0]={id,power:9999};assert.equal(total(s.current.arena),10124);assert.deepEqual(validState(s,ids),s);
const bad=structuredClone(s.current.arena);bad[0][1]={id,power:1};assert.throws(()=>validSquads(bad,'arena',ids));assert.throws(()=>validState({...s,version:2},ids));
const builds=[{id:'one',name:'闘技場テスト',mode:'arena',squads:s.current.arena},{id:'two',name:'にゃんうぉ',mode:'nyan',squads:blank('nyan')}];
const token=await encodeShare(builds);const decoded=await decodeShare(token,ids);assert.equal(decoded.length,2);assert.deepEqual(decoded[0].squads,builds[0].squads);assert.equal(decoded[0].name,builds[0].name);assert.throws(()=>validSquads([[{id:999999,power:1},null,null,null,null,null]],'nyan',ids));await assert.rejects(()=>decodeShare('broken',ids));
decoded[0].squads[0][0].power=1;assert.equal(builds[0].squads[0][0].power,125);
console.log('PASS: 234-card database, modes, power validation, totals, duplicate rules, backup validation, compressed multi-build sharing and copy independence');
const byId=new Map(data.cards.map(c=>[c.id,c]));
assert.equal(positionLabel(3),'前衛');assert.equal(positionLabel(4),'後衛');
assert.equal(data.cards[0].skillDetails.active[0].name,'俊敏性アップ');
assert.ok(data.cards.find(c=>c.id===533).skillDetails.passive[0].requiresRear);
assert.ok(data.cards.find(c=>c.id===533).skillDetails.unique[0].description.includes('TU'));
assert.ok(data.cards.every(c=>!c.skills.passive?.includes('増援')||c.skillDetails.passive.some(p=>p.requiresRear)));
const entry=data.cards.find(c=>c.skillDetails.passive.some(p=>p.requiresRear));
const board=blank('arena');board[0][0]={id:entry.id,power:100};board[0][4]={id,power:125};board[1][5]={id:entry.id,power:100};
const summary=skillSummary(board,byId);const entryName=entry.skillDetails.passive[0].name;const count=summary.groups.passive.find(s=>s.name===entryName);
assert.equal(count.count,2);assert.equal(count.front,1);assert.equal(count.rear,1);assert.equal(count.frontNeedsRear,1);assert.equal(summary.warnings.length,1);assert.equal(summary.warnings[0].squad,0);
assert.equal(skillSummary([board[1]],byId).warnings.length,0);
const html=formationExtras(board,byId);assert.ok(html.includes('前衛 · 1〜4'));assert.ok(html.includes('後衛 · 5〜6'));assert.ok(html.includes('スキル集計'));assert.equal((html.match(/class="compact-slot /g)||[]).length,24);
const variants=new Map([[1,{skillDetails:{passive:[{name:'スタンリベンジ',description:''}],active:[],unique:[]}}],[2,{skillDetails:{passive:[{name:'スタンリベンジ++',description:''}],active:[],unique:[]}}]]);
assert.equal(skillSummary([[{id:1},{id:2}]],variants).groups.passive.length,2);
console.log('PASS: front/rear boundaries, per-card and per-squad skill counts, entry conditions, distinct skill variants, 6-column previews');
