import assert from 'node:assert/strict';
import{validateSharedCard,createSharedCards}from'../dist/shared-cards.mjs';
import{filterCatalog,skillOptions}from'../dist/catalog-filters.mjs';
import{encodeOwned,decodeOwned}from'../dist/owned-share.mjs';
import {validImageSettings,cardImage,setImageSettings} from '../dist/card-images.mjs';
import {readPower,confirmedOwned} from '../dist/screenshot.mjs';
assert.deepEqual(readPower('8.7'),{raw:8.7,power:9,rounded:true});
assert.equal(readPower('468 331'),null);assert.equal(readPower('0'),null);
assert.deepEqual(confirmedOwned([{id:537,power:468,checked:true},{id:999,power:0,checked:false}],new Set([537])),{537:468});
assert.throws(()=>confirmedOwned([{id:537,power:468,checked:true},{id:537,power:331,checked:true}],new Set([537])));
import fs from 'node:fs';
import{fresh,blank,total,powerOK,validSquads,validState,encodeShare,decodeShare}from'../dist/core.mjs';
import{positionLabel,skillSummary}from'../dist/formation.mjs';
import{formationExtras}from'../dist/formation-view.mjs';
const data=JSON.parse(fs.readFileSync(new URL('../dist/data/cards.json',import.meta.url)));const ids=new Set(data.cards.map(c=>c.id));const id=data.cards.find(c=>c.id===537).id;
assert.equal(ids.size,data.cards.length);assert.equal(data.cards.length,296);assert.ok(data.cards.filter(c=>c.id<100000).every(c=>c.dataStatus==='complete'&&c.image.startsWith('https://')&&c.skills.active));
assert.equal(blank('nyan').length,1);assert.equal(blank('arena').length,4);assert.equal(blank('incident').length,4);
for(const p of [0,-1,10000,1.5,NaN])assert.equal(powerOK(p),false);for(const p of [1,125,9999])assert.ok(powerOK(p));
const s=fresh();s.owned[id]=125;s.current.arena[0][0]={id,power:125};s.current.arena[1][0]={id,power:9999};assert.equal(total(s.current.arena),10124);assert.deepEqual(validState(s,ids),s);
const received=decodeOwned(encodeOwned({537:468},'友達の手持ち'),ids);assert.deepEqual(received,{name:'友達の手持ち',owned:{537:468}});
received.owned[537]=1;assert.equal(s.owned[537],125);
assert.throws(()=>decodeOwned(encodeOwned({537:0},'invalid'),ids));assert.throws(()=>decodeOwned(encodeOwned({999999:5},'unknown'),ids));
assert.throws(()=>decodeOwned('broken',ids));
const allOwned=Object.fromEntries(data.cards.map(c=>[c.id,9999]));assert.ok(encodeOwned(allOwned,'全手持ち').length<12000);assert.deepEqual(decodeOwned(encodeOwned(allOwned,'全手持ち'),ids).owned,allOwned);
const custom={537:{zoom:1.5,x:-10,y:20,src:'data:image/jpeg;base64,YQ=='}};
assert.deepEqual(validState({...s,imageSettings:custom},ids).imageSettings,custom);
assert.throws(()=>validImageSettings({537:{zoom:0,x:0,y:0}},ids));
assert.throws(()=>validImageSettings({537:{zoom:1,x:0,y:0,src:'javascript:alert(1)'}},ids));
setImageSettings(custom);assert.ok(cardImage({id:537,name:'test',image:'original'}).includes('translate(-10%,20%) scale(1.5)'));setImageSettings({});
const bad=structuredClone(s.current.arena);bad[0][1]={id,power:1};assert.throws(()=>validSquads(bad,'arena',ids));assert.throws(()=>validState({...s,version:2},ids));
const builds=[{id:'one',name:'闘技場テスト',mode:'arena',squads:s.current.arena},{id:'two',name:'にゃんうぉ',mode:'nyan',squads:blank('nyan')}];
const token=await encodeShare(builds);const decoded=await decodeShare(token,ids);assert.equal(decoded.length,2);assert.deepEqual(decoded[0].squads,builds[0].squads);assert.equal(decoded[0].name,builds[0].name);assert.throws(()=>validSquads([[{id:999999,power:1},null,null,null,null,null]],'nyan',ids));await assert.rejects(()=>decodeShare('broken',ids));
decoded[0].squads[0][0].power=1;assert.equal(builds[0].squads[0][0].power,125);
console.log('PASS: 296-card database, modes, power validation, totals, duplicate rules, backup validation, compressed multi-build sharing and copy independence');
const byId=new Map(data.cards.map(c=>[c.id,c]));
const submitted={id:1000000,name:'追加テスト',cardName:'登録テスト',rarity:'SSR',attribute:'青',image:'data:image/jpeg;base64,YQ==',skillDetails:{passive:[{name:'スタンエントリー',description:'増援時に発動'}],active:[],unique:[]}};
const registered=validateSharedCard(submitted);assert.equal(registered.skillDetails.passive[0].requiresRear,true);assert.equal(registered.sourceUrl,null);
assert.throws(()=>validateSharedCard({...submitted,id:537}));assert.throws(()=>validateSharedCard({...submitted,rarity:'bad'}));
assert.throws(()=>validateSharedCard({...submitted,image:'javascript:alert(1)'}));
assert.throws(()=>validateSharedCard({...submitted,skillDetails:{}}));
const sharedCardClient=createSharedCards({enabled:true,url:'https://example.supabase.co',publishableKey:'sb_publishable_test'},async(url,options)=>Response.json(url.endsWith('builder_card_list')?[submitted]:{...JSON.parse(options.body).p_card,id:1000001}));
assert.equal((await sharedCardClient.list())[0].id,1000000);assert.equal((await sharedCardClient.add(submitted)).id,1000001);
const registeredIds=new Set([...ids,registered.id]);const customState=fresh();customState.owned[registered.id]=468;customState.current.nyan[0][0]={id:registered.id,power:468};assert.deepEqual(validState(customState,registeredIds),customState);
const customLink=await encodeShare([{name:'追加カードの編成',mode:'nyan',squads:customState.current.nyan}]);assert.equal((await decodeShare(customLink,registeredIds))[0].squads[0][0].id,registered.id);
const filterCards=[{id:1,name:'白波 蓮',rarity:'SSR',attribute:'緑',skillDetails:{passive:[{name:'スタン'}],active:[],unique:[]}},{id:2,name:'白波 蓮',rarity:'SR',attribute:'赤',skillDetails:{passive:[{name:'スタン++'}],active:[{name:'回復'}],unique:[]}},{id:3,name:'白波 蓮',rarity:'SSR',attribute:'緑',skillDetails:{passive:[{name:'スタン'}],active:[],unique:[]}}];
assert.deepEqual(filterCatalog(filterCards,{sort:'powerDesc'},{1:9,2:100},[1]).map(c=>c.id),[2,1,3]);
assert.deepEqual(filterCatalog(filterCards,{sort:'powerAsc'},{1:9,2:100},[2]).map(c=>c.id),[1,2,3]);
assert.deepEqual(filterCatalog(filterCards,{sort:'favorites'},{1:9,2:100},[2],true).map(c=>c.id),[2,1]);
assert.deepEqual(filterCatalog(filterCards,{q:'しらなみ',rarity:'SSR',attribute:'緑',skillCategory:'passive',skill:'スタン'},{1:9},[],true).map(c=>c.id),[1]);
assert.deepEqual(filterCatalog(filterCards,{skillCategory:'passive',skill:'回復'},{},[]).map(c=>c.id),[]);
assert.deepEqual(skillOptions(filterCards,'passive'),['スタン','スタン++']);
assert.equal(positionLabel(3),'前衛');assert.equal(positionLabel(4),'後衛');
assert.equal(data.cards.find(c=>c.id===537).skillDetails.active[0].name,'俊敏性アップ');
assert.ok(data.cards.find(c=>c.id===533).skillDetails.passive[0].requiresRear);
assert.ok(data.cards.find(c=>c.id===533).skillDetails.unique[0].description.includes('TU'));
assert.ok(data.cards.every(c=>!c.skills.passive?.includes('増援')||c.skillDetails.passive.some(p=>p.requiresRear)));
const entry=data.cards.find(c=>c.skillDetails.passive.some(p=>p.requiresRear));
const board=blank('arena');board[0][0]={id:entry.id,power:100};board[0][4]={id,power:125};board[1][5]={id:entry.id,power:100};
const summary=skillSummary(board,byId);const entryName=entry.skillDetails.passive[0].name;const count=summary.groups.passive.find(s=>s.name===entryName);
assert.equal(count.count,2);assert.equal(count.front,1);assert.equal(count.rear,1);assert.equal(count.frontNeedsRear,1);assert.equal(summary.warnings.length,1);assert.equal(summary.warnings[0].squad,0);
assert.equal(skillSummary([board[1]],byId).warnings.length,0);
const html=formationExtras(board,byId);assert.ok(html.includes('前衛 · 1〜4'));assert.ok(html.includes('後衛 · 5〜6'));assert.ok(html.includes('スキル集計'));assert.equal((html.match(/class="compact-slot /g)||[]).length,24);
const variants=new Map([[1,{skillDetails:{passive:[{name:'スタンリベンジ',description:''}],active:[],unique:[]}}],[2,{skillDetails:{passive:[{name:'スタンリベンジ++',description:''}],active:[],unique:[]}}]]);
assert.equal(skillSummary([[{id:1},{id:2}]],variants).groups.passive.length,2);
console.log('PASS: front/rear boundaries, per-card and per-squad skill counts, entry conditions, distinct skill variants, 6-column previews');

import{matchesCard,normalizeSearch,selectionPowerLabel}from'../dist/search.mjs';
const ren=data.cards.find(c=>c.id===537);assert.ok(matchesCard(ren,'しらなみ'));assert.ok(matchesCard(ren,'れん'));assert.ok(matchesCard(ren,'シラナミ レン'));assert.ok(matchesCard(ren,'白波蓮'));assert.ok(matchesCard(ren,'ｼﾗﾅﾐ'));assert.equal(matchesCard(ren,'しらなみ たいが'),false);assert.equal(normalizeSearch('ＳＴＵＮ'), 'stun');assert.ok(matchesCard({name:'針条 律',skills:{passive:'スタンリベンジ++'}},'しんじょう すたん'));assert.ok(matchesCard({name:'観月 累'},'みづき'));assert.equal(selectionPowerLabel(537,{537:125}),'登録戦力：125万');assert.equal(selectionPowerLabel(537,{}),'未所持・戦力未登録');
const audit=JSON.parse(fs.readFileSync(new URL('../card-audit.json',import.meta.url)));assert.equal(audit.addedCount,62);assert.equal(audit.unresolvedDetails.length,0);assert.equal(audit.existingMatched,233);assert.ok(audit.added.every(c=>byId.has(c.id)));assert.ok(data.cards.every(c=>c.skillDetails&&Array.isArray(c.skillDetails.passive)));console.log('PASS: full-list audit, 62 additions, kana/name matching, multiple search terms and owned selection power');
